TradeServices/UnicomWeb/Controllers/OutletDestinationValidationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Newtonsoft.Json;
using UnicomWeb.ModelForJS;
using TradeServices.Models;
using UnicomWeb.LocationService;

namespace UnicomWeb.Controllers
{
    public class OutletDestinationValidationController : Controller
    {
        // GET: OutletDestinationValidation
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public string GetAllRoutes()
        {
           Route[] routeArray = null;
            using (LocationService.LocationClient client = new LocationService.LocationClient())
            {
                client.Open();
                routeArray = client.GetAllActiveRoutes();
            }
            if (routeArray == null) throw new Exception("Не удалось получить маршруты");
            return JsonConvert.SerializeObject(GetRouteTreeList(routeArray, Guid.Empty));
            //return new JsonResult() {Data = GetRouteTreeList(routeArray, Guid.Empty)  , JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
        }

#if DEBUG
        [Authorize]
        public Route[] GetRoutes()
        {
            Route[] routeArray = null;
            using (LocationService.LocationClient client = new LocationService.LocationClient())
            {
                client.Open();
                routeArray = client.GetAllActiveRoutes();
            }
            return routeArray;
        }
#endif
        [Authorize]
        private  List<JsTreeNode> GetRouteTreeList(Route[] source, Guid parentId)
        {
            List<JsTreeNode> nodeList = new List<JsTreeNode>();
            var nodes = from node in source
                where node.ParentId == parentId
                select node;

            foreach (var node in nodes)
            {
                JsTreeNode newNode = new JsTreeNode()
                {
                    Text = node.Description,
                    Tags =new string[] { node.ParentId.ToString()},
                    Id = node.Id.ToString(),
                    Silent = true
                };

                if (source.Count(x => x.ParentId == node.Id) > 0)
                {
                    newNode.Nodes = GetRouteTreeList(source, node.Id);
                }
                nodeList.Add(newNode);
            }
            return nodeList;
        }

        [Authorize]
        public JsonResult GetRouteSet(string routeId, bool showOnlyUnknown)
        {
            if (routeId == null) routeId = Guid.Empty.ToString();
            RouteSet[] routeArray = null;
            using (LocationService.LocationClient client = new LocationService.LocationClient())
            {
                client.Open();
                routeArray = client.GetRouteSet(routeId);
            }
            if (routeArray == null) throw new Exception("Не удалось получить маршруты");
            return
               //JsonConvert.SerializeObject(from m in routeArray select new  {outletname = m.OutletName});
               // JsonConvert.SerializeObject(routeArray);
               new JsonResult() { Data = 
                (from r in routeArray
                 where (r.Longtitude == null && showOnlyUnknown) || !showOnlyUnknown
                 select r), JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
        }

        [Authorize]
        public JsonResult GetKnownLocation(string outletid)
        {
            KnownOutletLocation[] ol = null;
            using (LocationService.LocationClient client = new LocationService.LocationClient())
            {
                client.Open();
                ol = client.GetKnownLocation(outletid);
            }
            return new JsonResult() {Data = ol, JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue };
        }

        // [HttpPost]
        [Authorize]
        public bool SaveApprovedLocation(KnownOutletLocation location)
        {
            bool result = true;
            using (LocationService.LocationClient client = new LocationService.LocationClient())
            {
                client.Open();
                result = client.SaveApprovedLocation(location);
            }
            return result;
        }
    }
    
}

TradeServices/UnicomWeb/Controllers/RouteTripController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TradeServices.Models;
using UnicomWeb.LocationService;
//using UnicomWeb.Models;
using TradeUtils;
using UnicomWeb.ModelForJS;
using UnicomWeb.Enums;

namespace UnicomWeb.Controllers
{
    public class RouteTripController : Controller
    {
        // GET: RouteTrip
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult DailyRouteTrip(string routedate)
        {
            RouteTripEx[] tripArray = null;
            DateTime locDt = Convert.ToDateTime(routedate);
            using (LocationService.LocationClient client = new LocationService.LocationClient())
            {
                client.Open();
                tripArray = client.GetRouteTrip(locDt.ToString("ddMMyyyy"));
            }
            if (tripArray == null) return HttpNotFound();
            ViewBag.RouteDate = locDt.ToString("ddMMyyyy");
            ViewBag.SelectedDate = locDt.ToString("dd.MM.yyyy"); ;
            return PartialView(tripArray.Where(c => !String.IsNullOrEmpty(c.RouteName)));

        }

        [Authorize]
        public ActionResult CheckInMap(string routedate, string routeid, string routename)
        {
            ViewBag.RouteDate = routedate.ToDateTime().ToString("dd.MM.yyyy");
            ViewBag.RouteId = routeid;
            ViewBag.RouteName = routename;
            ViewBag.DisplayType = EnumDisplayRouteType.CheckIn.ToString();
            ModelOutletCheckInEx[] checkInArray = null;
            using (LocationService.LocationClient client = new LocationService.LocationClient())
            {
                client.Open();
                checkInArray = client.GetCheckIn(routedate, routeid);
            }
            if (checkInArray == null) return HttpNotFound();
            return View(checkInArray);

        }
        [Authorize]
        public ActionResult LocationMap(string routedate, string routeid, string routename)
        {
            ViewBag.RouteDate = routedate.ToDateTime().ToString("dd.MM.yyyy");
            ViewBag.RouteId = routeid;
            ViewBag.RouteName = routename;
            ViewBag.DisplayType = EnumDisplayRouteType.Trip.ToString();
            ModelOutletCheckInEx[] checkInArray = new ModelOutletCheckInEx[] { };
            //using (LocationService.LocationClient client = new LocationService.LocationClient())
            //{
            //    client.Open();
            //    checkInArray = client.GetCheckIn(routedate, routeid);
            //}
            //if (checkInArray == null) return HttpNotFound();
            return View("CheckInMap", checkInArray);

        }
        [Authorize]
        public ActionResult CheckInMapWithTrip(string routedate, string routeid, string routename)
        {
            ViewBag.RouteDate = routedate.ToDateTime().ToString("dd.MM.yyyy");
            ViewBag.RouteId = routeid;
            ViewBag.RouteName = routename;
            ViewBag.DisplayType = EnumDisplayRouteType.Both.ToString();
            ModelOutletCheckInEx[] checkInArray = null;
            using (LocationService.LocationClient client = new LocationService.LocationClient())
            {
                client.Open();
                checkInArray = client.GetCheckIn(routedate, routeid);
            }
            if (checkInArray == null) return HttpNotFound();
            return View("CheckInMap", checkInArray);

        }
        [Authorize]
        public JsonResult GetJSONCheckIn(string routedate, string idroute)
        {
            ModelOutletCheckInEx[] checkInArray = null;
            using (LocationService.LocationClient client = new LocationService.LocationClient())
            {
                client.Open();
                checkInArray = client.GetCheckIn(routedate.Replace(".",""), idroute);
            }
            if (checkInArray == null) throw new Exception("Не удалось получить массив отметок");
            int numb = 1;
            return Json(
                          from c in  checkInArray
                          orderby c.CheckInTime
                          select new JSOutletCheckIn
                          {
                              Outlet = c.Outlet,
                              OutletId = c.OutletId,
                              CheckInTime = c.CheckInTime,
                              CheckInTimeStr = c.CheckInTime.ToString("HH:mm"),
                              Id = c.Id,
                              Latitude = c.Latitude,
                              Longtitude = c.Longtitude,
                              CheckInNumber = numb++
                          }
                            , JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public JsonResult GetJSONTrip(string routedate, string idroute)
        {
            ModelRouteTripEx[] checkInArray = null;
            using (LocationService.LocationClient client = new LocationService.LocationClient())
            {
                client.Open();
                checkInArray = client.GetLocationTraking(routedate.Replace(".", ""), idroute);
            }
            if (checkInArray == null) throw new Exception("Не удалось получить массив отметок");
            int numb = 1;
            return new JsonResult(){
                Data = from c in checkInArray
                orderby c.CheckInTime
                select new ModelRouteTripEx
                {
                    CheckInTime = c.CheckInTime,
                    CheckInTimeString = c.CheckInTime.ToString("HH:mm:ss"),
                    Id = c.Id,
                    Latitude = c.Latitude,
                    Longtitude = c.Longtitude,
                    RowNum = numb++
                }
                            ,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet, MaxJsonLength = Int32.MaxValue};
        }
    }
}

TradeServices/UnicomWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Unicom</title>
    @*<style>
        ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background-color: black;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }

        li {
            float: left;
        }

            li a, .dropbtn {
                display: inline-block;
                color: lightgray;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
            }

                .dropbtn:hover {
                    background-color: gray;
                    color: #fff;
                    text-decoration:none
                }



            li .dropdown:hover {
                background-color: gray;
                color: green;
            }



            li.dropdown {
                display: inline-block;
            }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,1.6);
        }

            .dropdown-content a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                color: black;
                text-align: left;
            }

                .dropdown-content a:hover {
                    background-color: lightgray;
                    color: #000;
                }

        .dropdown:hover .dropdown-content {
            display: block;
        }
        .dropbtn {
                    display: inline-block;
                    color: lightgray;
                    text-align: center;
                    padding: 14px 16px;
                    text-decoration: none;
                }
    </style>*@
    @Styles.Render("~/Content/site.css")
    @Styles.Render("~/Content/bootstrap.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/gscommon")
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
</head>
<body>
@*<div>
            <ul class="ulmenumain">
                <li class="dropdown">@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="dropdown">
                    <a href="#" class="dropbtn">Навигация</a>
                    <div class="dropdown-content">
                        @Html.ActionLink("Пробег", "Index", "RouteTrip")
                        @Html.ActionLink("Валидация точек", "Index", "OutletDestinationValidation")
                    </div>
                </li>
            </ul>
    </div>*@


    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<a class="navbar-brand" href="/home/index">Home</a>*@
                @Html.ActionLink("Home", "Index", "Home", new object { },new { @class = "navbar-brand" })
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    @*<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>*@
                    @*<li><a href="#">Link</a></li>*@
                    @if (Request.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Навигация <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Пробег", "Index", "RouteTrip")</li>
                            
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Валидация точек", "Index", "OutletDestinationValidation")</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
                @*<ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Link</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                </ul>*@
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
        <div class="container ">
            @RenderBody()
        </div>
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - Unicom Trade</p>
    </footer>

</body>
</html>